export const SIGNUP = 'SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_ORGANIZERS = 'GET_ORGANIZERS';
export const GET_ORGANIZERS_REQUEST = 'GET_ORGANIZERS_REQUEST';
export const GET_ORGANIZERS_FAILURE = 'GET_ORGANIZERS_FAILURE';

export const GET_ORGANIZER_BY_ID = 'GET_ORGANIZER_BY_ID';
export const GET_ORGANIZER_BY_ID_REQUEST = 'GET_ORGANIZER_BY_ID_REQUEST';
export const GET_ORGANIZER_BY_ID_FAILURE = 'GET_ORGANIZER_BY_ID_FAILURE';
