export const SIGNUP = 'SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const AUTH_WITH_TOKEN = 'AUTH_WITH_TOKEN';
export const AUTH_WITH_TOKEN_REQUEST = 'AUTH_WITH_TOKEN_REQUEST';
export const AUTH_WITH_TOKEN_FAILURE = 'AUTH_WITH_TOKEN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_ORGANIZERS = 'GET_ORGANIZERS';
export const GET_ORGANIZERS_REQUEST = 'GET_ORGANIZERS_REQUEST';
export const GET_ORGANIZERS_FAILURE = 'GET_ORGANIZERS_FAILURE';

export const GET_ORGANIZER_BY_ID = 'GET_ORGANIZER_BY_ID';
export const GET_ORGANIZER_BY_ID_REQUEST = 'GET_ORGANIZER_BY_ID_REQUEST';
export const GET_ORGANIZER_BY_ID_FAILURE = 'GET_ORGANIZER_BY_ID_FAILURE';

export const NEW_ORGANIZER = 'NEW_ORGANIZER';
export const NEW_ORGANIZER_REQUEST = 'NEW_ORGANIZER_REQUEST';
export const NEW_ORGANIZER_FAILURE = 'NEW_ORGANIZER_FAILURE';

export const DELETE_ORGANIZER = 'DELETE_ORGANIZER';
export const DELETE_ORGANIZER_REQUEST = 'DELETE_ORGANIZER_REQUEST';
export const DELETE_ORGANIZER_FAILURE = 'DELETE_ORGANIZER_FAILURE';

export const NEW_SECTION = 'NEW_SECTION';
export const NEW_SECTION_REQUEST = 'NEW_SECTION_REQUEST';
export const NEW_SECTION_FAILURE = 'NEW_SECTION_FAILURE';
